added badges
Zheka1988/TestGuru pull request #17
Opened 2019-02-04 12:41 UTC by Zheka1988

2019-02-05 05:10 UTC, iBublik requested changes

2019-02-05 05:10 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +      flash["alert-success"] = t('.success')
Уже писал - не надо мешать типы флешей с css классами. Если поменяется css фреймворк, ты будешь везде менять названия флешей?

2019-02-05 05:10 UTC, iBublik commented on app/models/user.rb
> +
И зачем столько пустых строк?

2019-02-05 05:10 UTC, iBublik commented on app/services/reward_with_badges.rb
> +class RewardWithBadges
В именах классов не рекомендуется использовать глаголы

2019-02-05 05:10 UTC, iBublik commented on app/services/reward_with_badges.rb
> +      when 'category_complete'
Метод плохо расширяется - с появлением новых типов бейджей тут будет все больше `when`-ов. Лучше сделать как с валидациями в курсе по Ruby - там имя правила-проверки совпадало с типом валидации, что позволяло вызывать их через `send`

2019-02-05 05:10 UTC, iBublik commented on app/services/reward_with_badges.rb
> +    @user.badges << badge
Сервис станет удобнее, если он будет просто возвращать список доступных бейджей, не выдавая их. Так его можно легко протестировать и переиспользовать - например, выслать список пользователю на почту, вывести на страницу. Выдачу можно легко сделать в контроллере

2019-02-05 05:10 UTC, iBublik commented on app/services/reward_with_badges.rb
> +    successful_test? && @test.category.title == category
Раз у тебя все правила проверяют, что тест пройден успешно, это логично сделать до итерации бейджей, чтоб не делать лишней работы

2019-02-05 05:10 UTC, iBublik commented on app/services/reward_with_badges.rb
> +    successful_test? && @test.category.title == category
Бейдж выдается за _успешное_ прохождение _всех_ тестов категории

2019-02-05 05:10 UTC, iBublik commented on app/services/reward_with_badges.rb
> +    successful_test? && @test.level == level
Аналогично - нужно проверять, что успешно пройдены _все_ тесты данного уровня

2019-02-05 05:10 UTC, iBublik commented on app/views/admin/badges/_form.html.erb
> +      ['category_complete'],
В принципе, можно и так оставить, но желательно выводить админу читабельные типы правил

2019-02-05 16:31 UTC, iBublik requested changes

2019-02-05 16:31 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +      flash.alert = t('.success')
Зачем такой флеш отдельной строкой создавать? Можно короче `redirect_to ..., alert: ...`

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +class Award
BadgeService будет понятнее

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +  RULE = { "category_complete" => :category_complete, "first_try" => :first_try, "level_complete" => :level_complete }
Пустая строка после константы, `freeze` мутабельных объектов.
Это на будущее, в целом эта константа бесполезна

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +      send RULE[badge.rule], badge if successful_test?
1. В чем смысл мапинга? То же самое будет `send badge.rule, badge`
2. Проверку надо вне цикла делать, иначе в чем смысл? Тест не пройден, но ты все равно пройдешься по всем бейджам, чтоб не сделать _ничего_

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +    @user.badges << badge
https://github.com/Zheka1988/TestGuru/pull/17#discussion_r253735780

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +  def category_complete(badge)
Почему это публичный метод? И зачем вообще он нужен? Сделай, чтоб методы-предикаты всегда принимали параметр, даже если он не используется, и приводи параметр к нужному типу уже в методе-предикате

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +    cat_id = Category.find_by(title: category).id
А если такой категории не существует?

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +    Test.where(category_id: cat_id).count == @user.tests.where(category_id: cat_id).count
А что, если нет тестов с такой категорией? Юзер всегда будет получать бадж
Так же по кол-ву сравнивать некорректно - юзер может 10 раз пройти один и тот же тест. И вообще бейдж выдается за _успешное_ прохождение тестов определенной категории.

2019-02-05 16:31 UTC, iBublik commented on app/services/award.rb
> +    Test.where(level: level).count ==  @user.tests.where(level: level).count
Тут замечания аналогичны бейджу по категории

2019-02-06 17:49 UTC, iBublik requested changes

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +  def call
Этот метод и должен вернуть список бейджей, остальные пускай приватными будут

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +    if successful_test?
`return [] unless @test_passage.successfull?`

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +      Badge.all.each do |badge|
Для фильтрации коллекции есть метод `select` (`Badge.all.select { ... }`). Тебе как раз нужно выбрать (отфильтровать) бейджи

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +    @new_badges = []
В этой переменной нет нужды

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +    @user.badges << badge
Не надо 2 задачи разом решать. Бейджи можно выдать в контроллере, просто верни их список

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +    if category_exist?(badge)
Зачем 2 раза одно действие совершать? Записываешь результат поиск категории в переменную, проверяешь что там не nil, потом уже двигаешься дальше

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +    if tests_exist?(cat_id)
Я запутался от числа методов. Зачем столько? Достаточно по 1 методу-предикату на каждый тип правила

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +    Test.where(category_id: cat_id).each {|test| title_exist_test << test.title}
Во-первых, есть метод `map` для получение новой коллекции
Во-вторых, зачем что-то делать на Ruby, когда можно все на базе посчитать? Возьми число тестов с этой категорией и сравни с числом уникальных пройденных тестов пользователем. При прохождении теста сохраняй результат (успешно/не успешно) в базе - это позволит выбрать только успешные тесты. А для уникальности есть `distinct`

2019-02-06 17:49 UTC, iBublik commented on app/services/badge_service.rb
> +    Test.where(level: badge.parametr.to_i).each {|test| title_exist_test << test.title}
Опять же все аналогично бейджу по категориям

2019-02-07 18:16 UTC, iBublik requested changes

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +    if category
В реальности, конечно, вряд ли бы админу давали создать бейджи для несуществующий категории. Я бы убрал эту проверку, чтоб не усложнять код

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +  def category_complete(badge)
Методы-проверки являются предикатами, а их принято называть со знаком вопроса `?` в конце

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +      tests_exist(badge, cat_id)
Слишком много методово для тривиальной операции. Все это можно в `category_complete` перенести

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +    test = Test.find_by(category_id: cat_id)
Не нужно отдельно проверять налачие теста. Получи число тестов в этой категории, проверь что оно не 0 и уже потом можно сравнить это число с числом пользователя

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +      badge if all_tests_passed?(cat_id)
Метод должен вернуть логическое значение, а не badge

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +    Test.where(category_id: cat_id).count == @user.tests.where(category_id: cat_id).distinct.count
Нужно считать только _успешно пройденные тесты_ - это следует из условия задания. Чтоб было просто это сделать с помощью запроса, нужно кешировать результат прохождения в базе (при принятии ответа пишешь в базу результат true/false)

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +    badge if @user.tests.where(id: @test.id).count == 1
```suggestion
    @user.tests.where(id: @test.id).count == 1
```

2019-02-07 18:16 UTC, iBublik commented on app/services/badge_service.rb
> +    if Test.find_by(level: badge.parametr.to_i)
Аналогично бейджу по категории

2019-02-08 17:24 UTC, iBublik requested changes

2019-02-08 17:24 UTC, iBublik commented on app/models/test_passage.rb
> +    result >= 85 ? self.update(test_result: true) : false
Ээ, метод должен просто вернуть пройден ли тест, а не обновлять что-то в базе. Кешировать результат логично при принятии ответа

2019-02-08 17:24 UTC, iBublik commented on app/services/badge_service.rb
> +  def category_complete(badge)
> Методы-проверки являются предикатами, а их принято называть со знаком вопроса `?` в конце

Это не жесткое требование, но стоит следовать правилам, принятым в сообществе

2019-02-08 17:24 UTC, iBublik commented on app/services/badge_service.rb
> +    if number_tests
Ну если тут 0 будет, то условие все равно выполнится

2019-02-08 17:24 UTC, iBublik commented on app/services/badge_service.rb
> +    if number_tests
Ну если тут 0 будет, то условие все равно выполнится

2019-02-08 17:24 UTC, iBublik commented on app/services/badge_service.rb
> +    badge if @user.tests.where(id: @test.id).count == 1
Если ты не хочешь применять предложенное исправление, то хотя бы напиши почему, чтоб можно было подискутировать
> `@user.tests.where(id: @test.id).count == 1`

2019-02-08 17:24 UTC, iBublik commented on db/migrate/20190208061644_add_test_result_to_test_passages.rb
> +    add_column :test_passages, :test_result, :boolean, default: false
Глядя на поле `test_result` ожидаешь, что там будет какой-то балл или типа того. Если там логическое значение, то `success` понятнее

2019-02-09 12:06 UTC, Zheka1988 commented on app/models/test_passage.rb
> +    result >= 85 ? self.update(test_result: true) : false
Мы смотрим пройден тест в целом или нет, а не отдельный вопрос.  Присвоение идет в зависимости от набранных очков поэтому я считаю логично сделать это в данном методе или в методе где идет подсчет очков (result). Но чтоб было проще я сделал в passed.

2019-02-09 12:25 UTC, Zheka1988 commented on app/services/badge_service.rb
> +  def category_complete(badge)
В самом начале у меня были предикаты (https://github.com/Zheka1988/TestGuru/pull/17/commits/963b6ca5f1e281640d2682489fdc98752d18d27c). 
Мы переделали вызов таким образом **send badge.rule, badge** я не знаю как мне добавить знак вопроса в название вызываемого метода (типа так, что ли **send badge.rule+"?", badge**, чтобы вызывался метод предикат.

2019-02-09 12:25 UTC, Zheka1988 commented on app/services/badge_service.rb
> +    badge if @user.tests.where(id: @test.id).count == 1
Я упустил эту строчку

2019-02-10 06:22 UTC, iBublik commented on app/models/test_passage.rb
> +    result >= 85 ? self.update(test_result: true) : false
Состояние "Успешен или не успешен тест" может поменяться только при принятии ответа. Метод `success?` вообще является запросом и не может менять состояние. У тебя все завязано на том, что для кеширования результата нужно вызвать метод `success?`. Где гарантия, что этот метод вообще вызовется? Кешировать надо в том месте, где изменяется состояние. 
Еще одна проблема. Допустим, появится фича еженедельного дайджеста - пользователю отправляется письмо со списком тестов, которые он проходил, и там будет выводиться прошел он тест или нет. Ты будешь использовать метод `passed?`, при этом на каждый тест будет отправляться запрос в базу на обновление поля `test_result`, хотя это вовсе не нужно.

2019-02-10 06:23 UTC, iBublik commented on app/services/badge_service.rb
> +  def category_complete(badge)
> В самом начале у меня были предикаты ([963b6ca](https://github.com/Zheka1988/TestGuru/commit/963b6ca5f1e281640d2682489fdc98752d18d27c)).
> Мы переделали вызов таким образом **send badge.rule, badge** я не знаю как мне добавить знак вопроса в название вызываемого метода (типа так, что ли **send badge.rule+"?", badge**, чтобы вызывался метод предикат.

Ну да, badge.rule ведь обычная строка, значит можно использовать конкатенацию или интерполяци

2019-02-11 06:04 UTC, merged